### ISSUE TITLE
error on deploy and status

### ISSUE THREAD

**Issue by el-mich** [scttnlsn/dandelion#109]
Hi Scott,
getting the following error:

/Users/michel/.rvm/gems/ruby-1.9.2-p330/gems/dandelion-0.4.6/lib/dandelion/cli.rb:33:in `new': bad scan arg format: 10: (fatal)
	from /Users/michel/.rvm/gems/ruby-1.9.2-p330/gems/dandelion-0.4.6/lib/dandelion/cli.rb:33:in `repo'
	from /Users/michel/.rvm/gems/ruby-1.9.2-p330/gems/dandelion-0.4.6/lib/dandelion/cli.rb:37:in `workspace'
	from /Users/michel/.rvm/gems/ruby-1.9.2-p330/gems/dandelion-0.4.6/lib/dandelion/cli.rb:65:in `execute!'
	from /Users/michel/.rvm/gems/ruby-1.9.2-p330/gems/dandelion-0.4.6/bin/dandelion:8:in `<top (required)>'
	from /Users/michel/.rvm/gems/ruby-1.9.2-p330/bin/dandelion:23:in `load'
	from /Users/michel/.rvm/gems/ruby-1.9.2-p330/bin/dandelion:23:in `<main>'
	from /Users/michel/.rvm/gems/ruby-1.9.2-p330/bin/ruby_executable_hooks:15:in `eval'
	from /Users/michel/.rvm/gems/ruby-1.9.2-p330/bin/ruby_executable_hooks:15:in `<main>'

**Comment by scttnlsn** [comment]
Please re-open if this is still an issue.
