### ISSUE TITLE
Time Out Error?

### ISSUE THREAD

**Issue by bobrocke** [scttnlsn/dandelion#111]
When attempting to `dandelion deploy` I get this error:

```
/Users/bob/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/protocol.rb:153:in `read_nonblock': Operation timed out (Errno::ETIMEDOUT)
```

Do I have something misconfigured?

**Comment by scttnlsn** [comment]
@steffenr It's possible your FTP server is configured to use active FTP but a firewall is blocking the data port?  Are you able to connect successfully using other FTP clients?
