### ISSUE TITLE
error when install dandelion [windows]

### ISSUE THREAD

**Issue by leandroruel** [scttnlsn/dandelion#115]
I can not install dandelion with gem install, but any other yes.
when i search for dandelion in: rubygems.org, i can't find it. there is no more

**Comment by scttnlsn** [comment]
http://rubygems.org/gems/dandelion

I am able to install the gem via `gem install dandelion`.  Could you provide more info about your setup?

**Comment by leandroruel** [comment]
here the error, this happens only in Windows:
**leandro@LEANDRO-PC ~**
$ gem install dandelion
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing dandelion:
        ERROR: Failed to build gem native extension.

    c:/Ruby193/bin/ruby.exe -r ./siteconf20150108-3168-l0q6oo.rb extconf.rb
checking for cmake... no
ERROR: CMake is required to build Rugged.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=c:/Ruby193/bin/ruby

extconf failed, exit code 1

Gem files will remain installed in c:/Ruby193/lib/ruby/gems/1.9.1/gems/rugged-0.
21.3 for inspection.
Results logged to c:/Ruby193/lib/ruby/gems/1.9.1/extensions/x86-mingw32/1.9.1/ru
gged-0.21.3/gem_make.out

**Comment by scttnlsn** [comment]
Looks like you need to install CMake.  http://www.cmake.org/download/

**Comment by leandroruel** [comment]
weird, i installed other stuffs and it not happen

**Comment by scttnlsn** [comment]
@leandroruel I'm not sure what you mean.  Did that resolve your issue?

**Comment by ultraloveninja** [comment]
Yeah, I'm having the same issue. I downloaded CMake but I'm not too sure what I need to do next.

**Comment by ultraloveninja** [comment]
I had this same issue. I had to install cmake and pkg-config via homebrew so that Rugged could be installed.

**Comment by scttnlsn** [comment]
@leandroruel Please re-open if you're still having issues after installing cmake.
