### ISSUE TITLE
Multiple environments

### ISSUE THREAD

**Issue by ronlobo** [scttnlsn/dandelion#116]
Hi there,

it's possible to have multiple deploy configurations for different branches within one git project?

thanks in advance,

greets

**Comment by scttnlsn** [comment]
You can achieve this with multiple configuration files:

```
dandelion --config=dandelion-a.yml deploy branch-a
dandelion --config=dandelion-b.yml deploy branch-b
```

Please re-open if this does not work for your setup or you'd like to discuss alternate ways of handling this scenario.

**Comment by sebestenyb** [comment]
Would be nice to be able to define the source branch in the config, reducing the typing to
```
dandelion --config=dandelion-a.yml deploy
dandelion --config=dandelion-b.yml deploy
```

Would be awesome, if we could make branch specific setting blocks in the same config, reducing the typing to ``dandelion deploy`.


```
default:
	adapter: sftp
	host: example.com
	username: user
	password: pass
	path: path/to/production
develop:
	adapter: sftp
	host: example.com
	username: user
	password: pass
	path: path/to/staging
```

Cheers!
