### ISSUE TITLE
Issues with psych...?

### ISSUE THREAD

**Issue by ultraloveninja** [scttnlsn/dandelion#118]
If I run `dandelion stauts` or `dandelion deploy` I get this error:

    /Library/Ruby/Gems/2.0.0/gems/psych-2.0.12/lib/psych.rb:370:in `parse': (<unknown>): could not find expected ':' while scanning a simple key at line 12 column 5 (Psych::SyntaxError)
    from /Library/Ruby/Gems/2.0.0/gems/psych-2.0.12/lib/psych.rb:370:in `parse_stream'
    from /Library/Ruby/Gems/2.0.0/gems/psych-2.0.12/lib/psych.rb:318:in `parse'
    from /Library/Ruby/Gems/2.0.0/gems/psych-2.0.12/lib/psych.rb:245:in `load'
    from /Library/Ruby/Gems/2.0.0/gems/dandelion-0.4.9/lib/dandelion/config.rb:34:in `load'
    from /Library/Ruby/Gems/2.0.0/gems/dandelion-0.4.9/lib/dandelion/config.rb:10:in `initialize'
    from /Library/Ruby/Gems/2.0.0/gems/dandelion-0.4.9/lib/dandelion/cli.rb:15:in `new'
    from /Library/Ruby/Gems/2.0.0/gems/dandelion-0.4.9/lib/dandelion/cli.rb:15:in `config'
    from /Library/Ruby/Gems/2.0.0/gems/dandelion-0.4.9/lib/dandelion/cli.rb:21:in `adapter'
    from /Library/Ruby/Gems/2.0.0/gems/dandelion-0.4.9/lib/dandelion/cli.rb:37:in `workspace'
    from /Library/Ruby/Gems/2.0.0/gems/dandelion-0.4.9/lib/dandelion/cli.rb:69:in `execute!'
    from /Library/Ruby/Gems/2.0.0/gems/dandelion-0.4.9/bin/dandelion:8:in `<top (required)>'
    from /usr/bin/dandelion:23:in `load'
    from /usr/bin/dandelion:23:in `<main>'

I ran `gem install psych` just to make sure that I had psych installed and updated but still no luck.

I am missing something?

**Comment by scttnlsn** [comment]
That looks like you might have a syntax error in your YAML config file.  Could you verify that you're missing a colon (line 12, col 5)?

**Comment by ultraloveninja** [comment]
DAP!

Apparently there wasn't a space between the dash and an excluded item in my YAML config file.

Added the space and BLAMO! Worked.

Gotta say, this is pretty darn slick. Great work, thanks!
