### ISSUE TITLE
incompatible character encodings: ASCII-8BIT and US-ASCII

### ISSUE THREAD

**Issue by dbuurstede** [scttnlsn/dandelion#119]
I'm trying to deploy but i'm getting this error.

Remote revision:    a911b8f619864727f09cba480403e413758040d9
Deploying revision: be57bfac01c819b832b37e3e7ec7affd2a440d4a
Deploying changes...
/var/lib/gems/1.9.1/gems/dandelion-0.4.10/lib/dandelion/changeset.rb:37:in `expand_path': incompatible character encodings: ASCII-8BIT and US-ASCII (Encoding::CompatibilityError)
	from /var/lib/gems/1.9.1/gems/dandelion-0.4.10/lib/dandelion/changeset.rb:37:in `expand_path'
	from /var/lib/gems/1.9.1/gems/dandelion-0.4.10/lib/dandelion/changeset.rb:45:in `applicable?'
	from /var/lib/gems/1.9.1/gems/dandelion-0.4.10/lib/dandelion/changeset.rb:21:in `block in each'
	from /var/lib/gems/1.9.1/gems/dandelion-0.4.10/lib/dandelion/diff.rb:39:in `block in each'
	from /var/lib/gems/1.9.1/gems/dandelion-0.4.10/lib/dandelion/diff.rb:37:in `each'
	from /var/lib/gems/1.9.1/gems/dandelion-0.4.10/lib/dandelion/diff.rb:37:in `each'
	from /var/lib/gems/1.9.1/gems/dandelion-0.4.10/lib/dandelion/changeset.rb:20:in `each'
	from /var/lib/gems/1.9.1/gems/dandelion-0.4.10/lib/dandelion/deployer.rb:9:in `deploy_changeset!'
	from /var/lib/gems/1.9.1/gems/dandelion-0.4.10/lib/dandelion/command/deploy.rb:55:in `deploy_changeset!'
	from /var/lib/gems/1.9.1/gems/dandelion-0.4.10/lib/dandelion/command/deploy.rb:30:in `execute!'
	from /var/lib/gems/1.9.1/gems/dandelion-0.4.10/lib/dandelion/cli.rb:73:in `execute!'
	from /var/lib/gems/1.9.1/gems/dandelion-0.4.10/bin/dandelion:8:in `<top (required)>'
	from /usr/local/bin/dandelion:23:in `load'
	from /usr/local/bin/dandelion:23:in `<main>'

Allready did a new clone. All my other projects work great with dandelion! What can i do, anybody else had this problem?

**Comment by scttnlsn** [comment]
Could you try this on Ruby >= 1.9.3?  I suspect this could be related to Ruby 1.9.1

**Comment by dbuurstede** [comment]
I installed 1.9.3 but still the same problem. Anything else i can try?

**Comment by scttnlsn** [comment]
Maybe also try Ruby >= 2.0.0?  I'm not entirely sure here.

**Comment by scttnlsn** [comment]
Please re-open if this is still an issue.
