### ISSUE TITLE
error when deploy several files

### ISSUE THREAD

**Issue by leandroruel** [scttnlsn/dandelion#120]
i don't understand what's happening here, can someone give me a light here?

Dandelion error:

/usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/lib/dandelion/tree.rb:45:in `read': No such file or directory - ../d11wtq/boris/bin/boris (Errno::ENOENT)
	from /usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/lib/dandelion/tree.rb:45:in `symlink_content'
	from /usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/lib/dandelion/tree.rb:31:in `content'
	from /usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/lib/dandelion/tree.rb:23:in `data'
	from /usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/lib/dandelion/changeset.rb:27:in `block (2 levels) in each'
	from /usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/lib/dandelion/change.rb:12:in `call'
	from /usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/lib/dandelion/change.rb:12:in `data'
	from /usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/lib/dandelion/deployer.rb:49:in `deploy_change!'
	from /usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/lib/dandelion/deployer.rb:13:in `block in deploy_changeset!'
	from /usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/lib/dandelion/changeset.rb:28:in `block in each'
	from /usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/lib/dandelion/diff.rb:41:in `block in each'
	from /usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/lib/dandelion/diff.rb:37:in `each'
	from /usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/lib/dandelion/diff.rb:37:in `each'
	from /usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/lib/dandelion/changeset.rb:20:in `each'
	from /usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/lib/dandelion/deployer.rb:9:in `deploy_changeset!'
	from /usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/lib/dandelion/command/deploy.rb:55:in `deploy_changeset!'
	from /usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/lib/dandelion/command/deploy.rb:30:in `execute!'
	from /usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/lib/dandelion/cli.rb:69:in `execute!'
	from /usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/bin/dandelion:8:in `<top (required)>'
	from /usr/bin/dandelion:23:in `load'
	from /usr/bin/dandelion:23:in `<main>'

**Comment by scttnlsn** [comment]
You likely have a symlink committed to your Git repository that points to a file that no longer exists (`../d11wtq/boris/bin/boris`).  Is that the case?

**Comment by TheLonelyGhost** [comment]
For readability, the log file above:

```
/usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/lib/dandelion/tree.rb:45:in 'read': No such file or directory - ../d11wtq/boris/bin/boris (Errno::ENOENT) from /usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/lib/dandelion/tree.rb:45:in 'symlink_content'
from /usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/lib/dandelion/tree.rb:31:in 'content' from /usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/lib/dandelion/tree.rb:23:in 'data'
from /usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/lib/dandelion/changeset.rb:27:in block (2 levels) in 'each' from /usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/lib/dandelion/change.rb:12:in 'call'
from /usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/lib/dandelion/change.rb:12:in 'data' from /usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/lib/dandelion/deployer.rb:49:in 'deploy_change!'
from /usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/lib/dandelion/deployer.rb:13:in block in 'deploy_changeset!' from /usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/lib/dandelion/changeset.rb:28:inblock in 'each'
from /usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/lib/dandelion/diff.rb:41:in block in 'each' from /usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/lib/dandelion/diff.rb:37:in 'each'
from /usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/lib/dandelion/diff.rb:37:in 'each' from /usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/lib/dandelion/changeset.rb:20:in 'each'
from /usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/lib/dandelion/deployer.rb:9:in 'deploy_changeset!' from /usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/lib/dandelion/command/deploy.rb:55:in 'deploy_changeset!'
from /usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/lib/dandelion/command/deploy.rb:30:in 'execute!' from /usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/lib/dandelion/cli.rb:69:in 'execute!'
from /usr/lib/ruby/gems/1.9.1/gems/dandelion-0.4.6/bin/dandelion:8:in '<top (required)>' from /usr/bin/dandelion:23:in 'load'
from /usr/bin/dandelion:23:in ''
```

**Comment by leandroruel** [comment]
i'm not sure, but i will look for it again. thanks
