### ISSUE TITLE
Problems installing dandelion gem

### ISSUE THREAD

**Issue by andreybleme** [scttnlsn/dandelion#122]
Hi! 
I'm running Ubuntu 14.10. When I've tried to install the gem, an error occurred:

```shell
ERROR:  Error installing dandelion:
	ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.1 extconf.rb
checking for cmake... no
ERROR: CMake is required to build Rugged.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

```

It's probably a Ruby error, but I couldn't find help about it anywere.  Any idea?

Thanx!

**Comment by andreybleme** [comment]
I hadn't *cmake* installed bros ... I'm sorry about this.

BTW... A hint on the readme file about this requirement'd be handy ! ;)

**Comment by StudioLE** [comment]
I had this issue to, adding some troubleshooting to the README would really help
I also need `pkg-config`
```
apt-get install cmake pkg-config
```

**Comment by scttnlsn** [comment]
Updated the README with info about both `cmake` and `pkg-config`.

**Comment by EwanValentine** [comment]
I have both installed, still getting the same error?

**Comment by andreybleme** [comment]
@EwanValentine having *cmake* and *pkg-config* installed it shouldn't be happening. What's exactly the error?
