### ISSUE TITLE
Error 550

### ISSUE THREAD

**Issue by bobrocke** [scttnlsn/dandelion#125]
/Users/bob/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/ftp.rb:326:in `getresp': 550 Can't create directory: File exists (Net::FTPPermError)

I get the above error when attempting to upload with Dandelion. I saw some older, closed, issues, but none of the offered any solutions - the problems just "went away."

I'm using passive mode as one poster described.

**Comment by scttnlsn** [comment]
Does your FTP user have the proper permissions?  Have you tried w/ another FTP client?  More info would be great.

**Comment by bobrocke** [comment]
Everything else worked fine and worked to different directories on the same server. Another FTP client worked fine.

**Comment by joeserg** [comment]
Have you checked your path for a leading slash where there shouldn't be? I had a similar error message which went away once I changed: 

`path: /public_html/` 

to 

`path: public_html/`

**Comment by bobrocke** [comment]
@joeserg I think that was it! Thanks!
