### ISSUE TITLE
Dandelion error on deploy

### ISSUE THREAD

**Issue by duser0** [scttnlsn/dandelion#130]
Disclaimer: Please bear with me as not a backend guy!

Dandelion's been working fine for ages. Had some other issues so had to update my osx php and so had to reinstall that using homebrew etc... Now getting the following error when I try and deploy. 

Any ideas on what's going wrong?

But I tried updating Ruby and then the gems... Initially I had another error that said to install 'gem net-sftp'.  I have no idea what's happened or how to fix it :(

---

/Users/J/.rvm/gems/ruby-2.0.0-p353/gems/rugged-0.21.2/lib/rugged/rugged.bundle: dlopen(/Users/J/.rvm/gems/ruby-2.0.0-p353/gems/rugged-0.21.2/lib/rugged/rugged.bundle, 9): Library not loaded: /Users/J/.rvm/rubies/ruby-2.0.0-p353/lib/libruby.2.0.0.dylib (LoadError)
  Referenced from: /Users/J/.rvm/gems/ruby-2.0.0-p353/gems/rugged-0.21.2/lib/rugged/rugged.bundle
  Reason: image not found - /Users/J/.rvm/gems/ruby-2.0.0-p353/gems/rugged-0.21.2/lib/rugged/rugged.bundle
	from /Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:53:in `require'
	from /Users/J/.rvm/gems/ruby-2.0.0-p353/gems/rugged-0.21.2/lib/rugged.rb:5
	from /Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:53:in `gem_original_require'
	from /Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:53:in `require'
	from /Users/J/.rvm/gems/ruby-2.0.0-p353/gems/dandelion-0.4.9/lib/dandelion.rb:2
	from /Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:53:in `gem_original_require'
	from /Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:53:in `require'
	from /Users/J/.rvm/gems/ruby-2.0.0-p353/gems/dandelion-0.4.9/bin/dandelion:6
	from /Users/J/.rvm/gems/ruby-2.0.0-p353/bin/dandelion:23:in `load'
	from /Users/J/.rvm/gems/ruby-2.0.0-p353/bin/dandelion:23
	from /Users/J/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15

**Comment by scttnlsn** [comment]
Not really sure what's going on.  I would try reinstalling Ruby.  What did you have to reinstall via Homebrew?

**Comment by duser0** [comment]
I take it you mean why did I have to reinstall? I can't remember exactly now. It's all feeling around in the dark for me, so a bit of a blur. But whatever it was, it fixed it. But it's now created this problem with dandelion.

OK, so I just reinstalled Ruby. That was all good. I then reinstalled cmake using...

  brew install cmake

That was cool too. I'm now trying to install rugged but I get...

----

Fetching: rugged-0.22.2.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing rugged:
	ERROR: Failed to build gem native extension.

    /Users/J/.rvm/rubies/ruby-2.0.0-p645/bin/ruby -r ./siteconf20150605-56781-qfplzm.rb extconf.rb
checking for gmake... no
checking for make... yes
checking for cmake... yes
checking for pkg-config... yes
 -- cmake .. -DBUILD_CLAR=OFF -DTHREADSAFE=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS=-fPIC -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Unix Makefiles"
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/J/.rvm/rubies/ruby-2.0.0-p645/bin/ruby
	--use-system-libraries
extconf.rb:13:in `sys': ERROR: 'cmake .. -DBUILD_CLAR=OFF -DTHREADSAFE=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS=-fPIC -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Unix Makefiles"' failed (RuntimeError)
	from extconf.rb:66:in `block (2 levels) in <main>'
	from extconf.rb:65:in `chdir'
	from extconf.rb:65:in `block in <main>'
	from extconf.rb:62:in `chdir'
	from extconf.rb:62:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/J/.rvm/rubies/ruby-2.0.0-p645/lib/ruby/gems/2.0.0/gems/rugged-0.22.2 for inspection.
Results logged to /Users/J/.rvm/rubies/ruby-2.0.0-p645/lib/ruby/gems/2.0.0/extensions/x86_64-darwin-11/2.0.0/rugged-0.22.2/gem_make.out

------

I take it rugged is causing the issue?

**Comment by scttnlsn** [comment]
Yeah, make sure you can run `gem install rugged -v 0.22.2`.  If that fails I'd suggest opening an issue on the Rugged issue tracker: https://github.com/libgit2/rugged  If that succeeds but `gem install dandelion` fails please re-open this issue.

**Comment by duser0** [comment]
Hey Scott

Managed to fix it :)

I just updated to the latest possible XCode 4.6.3 (as I'm running Lion) and that fixed the problem! I could then install rugged, then dandelion and net-sftp and dandelion deploys again.

**Comment by scttnlsn** [comment]
Great!  Glad to hear it's working for you now.
