### ISSUE TITLE
Message: Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text.

### ISSUE THREAD

**Issue by ogrosko** [scttnlsn/dandelion#131]
Hey

After dandelion configuration I ran dandelion status, then I got message "Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text." and password asking. When I insert correct password I get: "Authentication failed for user sbund@www.servicebund.de (Net::SSH::AuthenticationFailed)"

I'm sure password and host is correct

Do you have any idea where could be the problem

Thanks

dandelion -v : 0.4.14

**Comment by scttnlsn** [comment]
Are you using the `sftp` adapter?

**Comment by ogrosko** [comment]
Yes

**Comment by scttnlsn** [comment]
I can't reproduce this.  What are the details of your setup?  i.e. What is the remote SSH/SFTP software?

**Comment by ogrosko** [comment]
I have no problems with SSH/SFTP clients even with other dandelion configs it work fine

Here dandelion.yml config:

adapter: sftp
host: XXX
username: XXX
password: XXX
path: public_html/www
passive: true

exclude:
    - .git/
    - .grunt/
    - sql/
    - node_modules/
    - .gitignore
    - .gitmodules
    - .htaccess
    - .htpasswd
    - dandelion.yml

To the mentioned server I can connect with no problems using FileZilla or terminal

**Comment by jpgdcl** [comment]
I had the same problem and managed to solve it. 

It was because the password in the `dandelion.yml` config file was incorrect.
