### ISSUE TITLE
Deployment path question

### ISSUE THREAD

**Issue by medinlu** [scttnlsn/dandelion#141]
I have a git folder structure like this:
- .git
- dandelion.yml
- dist
   -library/css
   -library/js
   -library/img
 index.html
- src

A gulp task copies some files from src to dist, but my git repo is on the root as you can see.

I want to deploy only the files inside dist folder to the root on my server, but I can't figure out how to do it. I'm trying this option inside the dandelion.yml

path_map:
  - dist: /

But I'm still getting the same on the server. A folder called dist is created.

My current solution is a second git repository inside the dist folder with another dandelion.yml, but I think this shouldn't be necessary, and is not really an elegant solution because I will have conflicts with my current gulp tasks.

Any idea to solve this?

Thanks!

**Comment by scttnlsn** [comment]
`path_map` is not currently implemented (just discussed in https://github.com/scttnlsn/dandelion/issues/95).

You should currently be able to specify `local_path: dist` and `path: /`

**Comment by medinlu** [comment]
Cheers man, Thanks.
