### ISSUE TITLE
Heroku gives wrongly formatted error vs Local (Windows/Linux) is working fine

### ISSUE THREAD

**Issue by jkathiresan** [scttnlsn/dandelion#143]
The application works fine locally. However deploying it in heroku gives the following error without any clue

com.github.dandelion.core.DandelionException: The file 'WEB-INF/classes/dandelion/my-bundle.json' is wrongly formatted.

Below is the JSON file for reference used in the deployment for your reference.

{
"bundle" : "my-bundle",
"assets": [
    {
        "name": "jquery",
        "version": "2.1.1",
        "type": "js",
        "locations": {
            "webapp": "/webjars/jquery/2.1.1/jquery.min.js"
        }
    },
    {
        "name": "datatables",
        "version": "1.10.5",
        "type": "js",
        "locations": {
            "webapp": "/webjars/datatables/1.10.5/js/jquery.dataTables.js"
        }
    },
    {
        "name": "datatables",
        "version": "1.10.5",
        "type": "css",
        "locations": {
            "webapp": "/webjars/datatables/1.10.5/css/jquery.dataTables.css"
        }
    }
]
}

Other Information:
There is no illegal character in the file
There is no BOM character in the file

We have tried many times with no success. Not sure it's a known bug or it's had a fix.

Thanks.

**Comment by scttnlsn** [comment]
I think you're using a different projected named "Dandelion".  Try filing an issue here: https://github.com/dandelion/dandelion
