### ISSUE TITLE
Issue with El Capitan

### ISSUE THREAD

**Issue by nathanaelphilip** [scttnlsn/dandelion#144]
Dandelion isn’t found any more and when I try to reinstall I get an error.

**Comment by scttnlsn** [comment]
Could you post the error here?

**Comment by nathanaelphilip** [comment]
Building native extensions.  This could take a while...
ERROR:  Error installing dandelion:
	ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -r ./siteconf20151001-11038-4otbip.rb extconf.rb
checking for gmake... no
checking for make... yes
checking for cmake... yes
checking for pkg-config... yes
 -- cmake .. -DBUILD_CLAR=OFF -DTHREADSAFE=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS=-fPIC -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Unix Makefiles"
 -- /usr/bin/make
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
	--use-system-libraries
extconf.rb:13:in `sys': ERROR: '/usr/bin/make' failed (RuntimeError)
	from extconf.rb:67:in `block (2 levels) in <main>'
	from extconf.rb:65:in `chdir'
	from extconf.rb:65:in `block in <main>'
	from extconf.rb:62:in `chdir'
	from extconf.rb:62:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/rugged-0.22.1b1 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-15/2.0.0/rugged-0.22.1b1/gem_make.out

**Comment by scttnlsn** [comment]
You may need to reinstall Xcode and/or the command-line tools provided by Xcode.

**Comment by nathanaelphilip** [comment]
I just installed the command-line tools and restarted, but i’m still getting errors:

ERROR:  Error installing dandelion:
	ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -r ./siteconf20151001-1479-1roy55l.rb extconf.rb
checking for gmake... no
checking for make... yes
checking for cmake... yes
checking for pkg-config... yes
 -- cmake .. -DBUILD_CLAR=OFF -DTHREADSAFE=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS=-fPIC -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Unix Makefiles"
 -- /usr/bin/make
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
	--use-system-libraries
extconf.rb:13:in `sys': ERROR: '/usr/bin/make' failed (RuntimeError)
	from extconf.rb:67:in `block (2 levels) in <main>'
	from extconf.rb:65:in `chdir'
	from extconf.rb:65:in `block in <main>'
	from extconf.rb:62:in `chdir'
	from extconf.rb:62:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/rugged-0.22.1b1 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-15/2.0.0/rugged-0.22.1b1/gem_make.out

**Comment by nathanaelphilip** [comment]
Would it have something to do with this: http://pointlessramblings.com/posts/El_Capitan/

**Comment by nathanaelphilip** [comment]
```
gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
```

**Comment by nathanaelphilip** [comment]
```
make -v
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```

**Comment by nathanaelphilip** [comment]
sorry so many messages, just trying to give you as much info as possible:

```
~ which gcc
/usr/bin/gcc
```

**Comment by steffenr** [comment]
Same problem here with a fresh install of El Capitain and dandelion.

**Comment by nathanaelphilip** [comment]
@steffenr did you install XCode Command Line tools?

**Comment by nathanaelphilip** [comment]
@scttnlsn do you think it has to do with the version of Ruby? Is there a specific version you recommend?

**Comment by joernba** [comment]
I have the exact same problem as well. Command line tools installed, using rvm though.

**Comment by nathanaelphilip** [comment]
Anyone get anywhere?

**Comment by nathanaelphilip** [comment]
I’m getting this in the mkmf.log

```
[ 99%] Building C object CMakeFiles/git2.dir/src/hash/hash_generic.c.o
In file included from /Users/nathanaelmoody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rugged-0.22.1b1/vendor/libgit2/src/hash/hash_generic.c:10:
/Users/nathanaelmoody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rugged-0.22.1b1/vendor/libgit2/src/hash/hash_generic.h:13:8: error: redefinition of 'git_hash_ctx'
struct git_hash_ctx {
       ^
/Users/nathanaelmoody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rugged-0.22.1b1/vendor/libgit2/src/hash/hash_common_crypto.h:15:8: note: previous definition is here
struct git_hash_ctx {
       ^
/Users/nathanaelmoody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rugged-0.22.1b1/vendor/libgit2/src/hash/hash_generic.c:121:11: error: no member named 'H' in 'struct git_hash_ctx'
        A = ctx->H[0];
            ~~~  ^
/Users/nathanaelmoody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rugged-0.22.1b1/vendor/libgit2/src/hash/hash_generic.c:122:11: error: no member named 'H' in 'struct git_hash_ctx'
        B = ctx->H[1];
            ~~~  ^
/Users/nathanaelmoody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rugged-0.22.1b1/vendor/libgit2/src/hash/hash_generic.c:123:11: error: no member named 'H' in 'struct git_hash_ctx'
        C = ctx->H[2];
            ~~~  ^
/Users/nathanaelmoody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rugged-0.22.1b1/vendor/libgit2/src/hash/hash_generic.c:124:11: error: no member named 'H' in 'struct git_hash_ctx'
        D = ctx->H[3];
            ~~~  ^
/Users/nathanaelmoody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rugged-0.22.1b1/vendor/libgit2/src/hash/hash_generic.c:125:11: error: no member named 'H' in 'struct git_hash_ctx'
        E = ctx->H[4];
            ~~~  ^
/Users/nathanaelmoody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rugged-0.22.1b1/vendor/libgit2/src/hash/hash_generic.c:217:7: error: no member named 'H' in 'struct git_hash_ctx'
        ctx->H[0] += A;
        ~~~  ^
/Users/nathanaelmoody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rugged-0.22.1b1/vendor/libgit2/src/hash/hash_generic.c:218:7: error: no member named 'H' in 'struct git_hash_ctx'
        ctx->H[1] += B;
        ~~~  ^
/Users/nathanaelmoody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rugged-0.22.1b1/vendor/libgit2/src/hash/hash_generic.c:219:7: error: no member named 'H' in 'struct git_hash_ctx'
        ctx->H[2] += C;
        ~~~  ^
/Users/nathanaelmoody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rugged-0.22.1b1/vendor/libgit2/src/hash/hash_generic.c:220:7: error: no member named 'H' in 'struct git_hash_ctx'
        ctx->H[3] += D;
        ~~~  ^
/Users/nathanaelmoody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rugged-0.22.1b1/vendor/libgit2/src/hash/hash_generic.c:221:7: error: no member named 'H' in 'struct git_hash_ctx'
        ctx->H[4] += E;
        ~~~  ^
/Users/nathanaelmoody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rugged-0.22.1b1/vendor/libgit2/src/hash/hash_generic.c:224:5: error: redefinition of 'git_hash_init'
int git_hash_init(git_hash_ctx *ctx)
    ^
/Users/nathanaelmoody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rugged-0.22.1b1/vendor/libgit2/src/hash/hash_common_crypto.h:23:17: note: previous definition is here
GIT_INLINE(int) git_hash_init(git_hash_ctx *ctx)
                ^
/Users/nathanaelmoody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rugged-0.22.1b1/vendor/libgit2/src/hash/hash_generic.c:226:7: error: no member named 'size' in 'struct git_hash_ctx'
        ctx->size = 0;
        ~~~  ^
/Users/nathanaelmoody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rugged-0.22.1b1/vendor/libgit2/src/hash/hash_generic.c:229:7: error: no member named 'H' in 'struct git_hash_ctx'
        ctx->H[0] = 0x67452301;
        ~~~  ^
/Users/nathanaelmoody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rugged-0.22.1b1/vendor/libgit2/src/hash/hash_generic.c:230:7: error: no member named 'H' in 'struct git_hash_ctx'
        ctx->H[1] = 0xefcdab89;
        ~~~  ^
/Users/nathanaelmoody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rugged-0.22.1b1/vendor/libgit2/src/hash/hash_generic.c:231:7: error: no member named 'H' in 'struct git_hash_ctx'
        ctx->H[2] = 0x98badcfe;
        ~~~  ^
/Users/nathanaelmoody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rugged-0.22.1b1/vendor/libgit2/src/hash/hash_generic.c:232:7: error: no member named 'H' in 'struct git_hash_ctx'
        ctx->H[3] = 0x10325476;
        ~~~  ^
/Users/nathanaelmoody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rugged-0.22.1b1/vendor/libgit2/src/hash/hash_generic.c:233:7: error: no member named 'H' in 'struct git_hash_ctx'
        ctx->H[4] = 0xc3d2e1f0;
        ~~~  ^
/Users/nathanaelmoody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rugged-0.22.1b1/vendor/libgit2/src/hash/hash_generic.c:238:5: error: redefinition of 'git_hash_update'
int git_hash_update(git_hash_ctx *ctx, const void *data, size_t len)
    ^
/Users/nathanaelmoody/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rugged-0.22.1b1/vendor/libgit2/src/hash/hash_common_crypto.h:30:17: note: previous definition is here
GIT_INLINE(int) git_hash_update(git_hash_ctx *ctx, const void *data, size_t len)
                ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [CMakeFiles/git2.dir/src/hash/hash_generic.c.o] Error 1
make[1]: *** [CMakeFiles/git2.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by nathanaelphilip** [comment]
@scttnlsn switched to git-ftp & gulp. A little different workflow. If you decide to fix the issue, please let us know!

**Comment by joernba** [comment]
I think this should be reopened. There are more people having the same problem with El Capitan.

**Comment by lourou** [comment]
+1 Yes, this issue should be reopened. Many people are facing this.

**Comment by scttnlsn** [comment]
I haven't updated OS X yet and so can't really debug this very well.  It's definitely on my radar though and I'll look into it soon.

**Comment by scttnlsn** [comment]
This looks like an issue compiling libgit2 (a native dependency of the Rugged gem).  Does everyone have the same issue during a `gem install rugged -v 0.22.1b1`?  Perhaps this should be reported to the Rugged project (https://github.com/libgit2/rugged).

**Comment by nathanaelphilip** [comment]
Is there something specific I need to say to them? Should I paste my mkmf.log file in the comment?

**Comment by swist666** [comment]
I have the same problem. I also have an issue with version Rugged 0.22.1b1 but most recent works correctly (0.23.2).

**Comment by nathanaelphilip** [comment]
@swist666 did you just update the rugged gem?

**Comment by swist666** [comment]
I have installed it by: `gem install rugged`
When i try to `gem install rugged -v 0.22.1b1` I get an error.

**Comment by scttnlsn** [comment]
I'll try updating Dandelion's Rugged dependency

**Comment by scttnlsn** [comment]
Released Dandelion 0.4.15 that now depends on Rugged 0.23.2.  Please let me know if this addresses the installation issue on El Captain.

**Comment by nathanaelphilip** [comment]
works!

**Comment by scttnlsn** [comment]
Huzzah!  Please re-open if there are any more issues w/ El Captain.

**Comment by lourou** [comment]
Thanks :) works like a charm
