### ISSUE TITLE
Set revision on server

### ISSUE THREAD

**Issue by alexelash** [scttnlsn/dandelion#147]
Hi,

I'm actually moving from Springloops.io to using Bitbucket. I've moved a project (that was already deployed to the Live server) to Bitbucket, and would now like to test deploying using Dandelion. 

My question is: is there a way (as on Springloops, screenshot attached):
![screen shot 2015-11-10 at 10 24 12 am](https://cloud.githubusercontent.com/assets/5672295/11066201/3564ce8e-8795-11e5-99d5-3abfd1111b84.jpg)
 to put in the Dandelion.yml file that this is not the first deployment? When I ran a dry run, of course Dandelion showed that it would put up allllll of the files in my most recent revision. Is the below (from the docs) what I need to use?

![screen shot 2015-11-10 at 10 24 38 am](https://cloud.githubusercontent.com/assets/5672295/11066210/443f8d5e-8795-11e5-85f1-7a4ec4525a69.jpg)

Thanks! Sorry for the likely n00b question.

**Comment by scttnlsn** [comment]
I believe `dandelion init <revision>` is what you're looking for.  This will simply write the given revision SHA into the remote `.revision` file.

The `revision_file` configuration option is to specify the remote revision filename (the default is `.revision`).

Hope that helps!

**Comment by alexelash** [comment]
Thank you so much! This is extremely helpful.
