### ISSUE TITLE
Dandelion seems to deploy, but files don't change

### ISSUE THREAD

**Issue by alexelash** [scttnlsn/dandelion#148]
I've been trying to deploy a revision with no success. I wonder if it has to do with the fact that I had deployed this project through a different deployment method (used Springloops UI). For this project, I initially ran `dandelion init <version>` after creating my `dandelion.yml` file:

```shell
adapter: ftp
host:  <hostname>
username: <username>
password: <password>
path: public_html
exclude:
    - .gitignore
    - dandelion.yml
    - branches/
    - tags/
    - trunk/cache/
```

All seemed to be well, as I connected to the server without issue and `dandelion status` told me that the remote revision was what I had set it to. When running `dandelion deploy --dry-run`, I saw the file that needed to be changed. Same with `dandelion deploy`. Deploying threw no errors at all, and in fact the revision updated on the server... but manually checking the file told me that my changes didn't go through. My git version is 2.3.8 (Apple Git-58) and Dandelion version is 0.4.15. 

I hope that this makes sense to you! I couldn't find anything that was quite my issue in here.

**Comment by scttnlsn** [comment]
Hmm, that's curious.  Not sure how to debug this since I cannot reproduce the issue.  Can you try uploading one of the changed files w/ another FTP client?  This way we can rule out an issue w/ the server.

**Comment by alexelash** [comment]
Totally understand. I was hoping that I'd writing something wrong in my `dandelion.yml` file without realizing it, to be honest. Uploading/overwriting the file (`style.css` in this case) through Transmit was successful.

**Comment by alexelash** [comment]
Not sure if this is relevant, but I had put my password in quotes. Looking at the docs, I see that they aren't in quotes. Now when I run `dandelion status`, I do get an error (see attached).
![screen shot 2015-11-10 at 1 15 17 pm](https://cloud.githubusercontent.com/assets/5672295/11071129/20a4a2fe-87ad-11e5-8d51-f482e53f08ca.jpg)

**Comment by scttnlsn** [comment]
Password in quotes shouldn't matter.  To deal with the 425 you may want to try setting `passive: true` in your `dandelion.yml` file.  Still not sure why the file contents would not be updated.

**Comment by alexelash** [comment]
Alright, I got it working now. Still a bit mysterious to me!
- Password without quotes
- `Passive: true`
Maybe passive needed to be set to true?

**Comment by scttnlsn** [comment]
Files are uploading too?

**Comment by alexelash** [comment]
Oh man, I feel silly. I see what the problem was. Actually, not sure why deployments seemed to work.
I'm deploying the contents of a trunk/ folder, but never set `local_path: trunk`. Now that I have done so, I was able to upload a new file.
