### ISSUE TITLE
Getting (Errno::EPERM) when installing

### ISSUE THREAD

**Issue by ultraloveninja** [scttnlsn/dandelion#149]
I upgraded to El Cap and it must have blown out the install for dandelion.
I'm trying to install it again, but when I do, I'm getting this error:

```
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/dandelion
```

Not too sure what could be triggering that. I updated my ruby packages, so I'm starting to think that it has something to do with permissions...?

Any insight would be great, thanks!

**Comment by ultraloveninja** [comment]
Welp, I did some more digging and it looks like that El Cap is using some sort of updated security feature called System Integrity Protection (SIP) which doesn't allow you to automatically install to the root:

http://stackoverflow.com/questions/32891965/error-while-executing-gem-errnoeperm-operation-not-permitted

I got it installed eventually, but then try to build out the atomic and json gems are getting tricky.

**Comment by scttnlsn** [comment]
OK, glad you figured it out.  I'm going to close this since it doesn't seem to pertain to Dandelion specifically.
