### ISSUE TITLE
error: no implicit conversion

### ISSUE THREAD

**Issue by xavierartot** [scttnlsn/dandelion#150]
Hi,
I have this:

dandelion init
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/net/ftp.rb:466:in `+': no implicit conversion of Fixnum into String (TypeError)
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/net/ftp.rb:466:in `block in login'
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/net/ftp.rb:462:in `login'
	from /usr/local/lib/ruby/gems/2.2.0/gems/dandelion-0.4.16/lib/dandelion/adapter/ftp.rb:57:in `ftp_client'
	from /usr/local/lib/ruby/gems/2.2.0/gems/dandelion-0.4.16/lib/dandelion/adapter/ftp.rb:17:in `initialize'
	from /usr/local/lib/ruby/gems/2.2.0/gems/dandelion-0.4.16/lib/dandelion/adapter.rb:24:in `new'
	from /usr/local/lib/ruby/gems/2.2.0/gems/dandelion-0.4.16/lib/dandelion/adapter.rb:24:in `create_adapter'
	from /usr/local/lib/ruby/gems/2.2.0/gems/dandelion-0.4.16/lib/dandelion/cli.rb:21:in `adapter'
	from /usr/local/lib/ruby/gems/2.2.0/gems/dandelion-0.4.16/lib/dandelion/cli.rb:37:in `workspace'
	from /usr/local/lib/ruby/gems/2.2.0/gems/dandelion-0.4.16/lib/dandelion/cli.rb:69:in `execute!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/dandelion-0.4.16/bin/dandelion:8:in `<top (required)>'
	from /usr/local/bin/dandelion:23:in `load'
	from /usr/local/bin/dandelion:23:in `<main>'
	
same with status and dploy?

Thanks

**Comment by xavierartot** [comment]
Error password

**Comment by scttnlsn** [comment]
@xavierartot Could you elaborate on how you solved the issue in case others run into this?  Was the only issue that you had the wrong password in your `dandelion.yml` file?

**Comment by xavierartot** [comment]
Error with my password

**Comment by scttnlsn** [comment]
Hmm, OK.  That's a strange error message for a bad password.  Thanks.

**Comment by xavierartot** [comment]
I'm on MAC, I aggree with that.
