### ISSUE TITLE
folder missing

### ISSUE THREAD

**Issue by xavierartot** [scttnlsn/dandelion#151]
Hi,
I have some folder and they not transfert in the server:
dist/
node_modules/
?
Thanks

**Comment by scttnlsn** [comment]
Are those directories in your `.gitignore`?

**Comment by xavierartot** [comment]
arf. thanks, it was in the gitignore.

**Comment by scttnlsn** [comment]
You can add those directories to the `additional` section of your `dandelion.yml` but beware that the full contents will be uploaded each time (since Dandelion has no way to figure out what changed).
