### ISSUE TITLE
Specify Dev and Live server

### ISSUE THREAD

**Issue by ultraloveninja** [scttnlsn/dandelion#155]
Is there a way to specify in the config file a dev and live server and then use something like `dandelion deploy live` for the live server or `dandelion deploy dev` for the dev server?
Wasn't sure if this was possible. Thanks!

**Comment by scttnlsn** [comment]
You can create a separate config file for each environment and then deploy to each by running:

    dandelion --config=dandelion-dev.yml deploy
    dandelion --config=dandelion-live.yml deploy

There's some related discussion here: https://github.com/scttnlsn/dandelion/issues/96
