### ISSUE TITLE
Changing Permissions

### ISSUE THREAD

**Issue by jpgdcl** [scttnlsn/dandelion#156]
I'm finding that sometimes some of my files seem to change permissions between the local version and production version. 

Trying to track down what it might be. Is there anything in Dandelion that could possibly be causing this? 

Cheers

**Comment by scttnlsn** [comment]
What adapter are you using?  Some of the adapters currently support preserving permissions by setting `preserve_permissions: true` in your config file.

**Comment by jpgdcl** [comment]
Ah okay, nice. I'm using `scheme: sftp`

**Comment by scttnlsn** [comment]
Please re-open this issue if you continue to have trouble despite adding `preserve_permissions: true` to your config file.
