### ISSUE TITLE
Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text.

### ISSUE THREAD

**Issue by Bobz-zg** [scttnlsn/dandelion#160]
Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text.
Enter passphrase for /Users/xyz/.ssh/id_rsa:

Started to happen in last couple of days.
I have checked my u/p they both work fine when using Transmit to connect.

Not sure how to debug this?

Dandelion 0.5.0
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
OSX 10.12

**Comment by scttnlsn** [comment]
This should be resolved by https://github.com/scttnlsn/dandelion/commit/5ccd7b5b7cd0426d27f9c24a93850ddbb331116b
