### ISSUE TITLE
Problems deploying to PHP 7 server

### ISSUE THREAD

**Issue by kevwaddell** [scttnlsn/dandelion#161]
Hi, I currently host several sites on WPEngine and use dandelion to deploy my themes from local to production and staging. WPEngine have upgraded there servers to PHP 7 and all my sites now run on it. 

After this upgrade I found that dandelion only deploys a few files then creates a net-ssh error (I have attached the terminal output). 

I also contacted WPEngine support to see if it was a problem on their end they tried the script and couldn't get it to work either. They suggested I contacted the developer to see if it was compatible with PHP 7. 

I hope you can sort this as I use dandelion on all my deployments.

![screenshot 2017-03-08 10 29 56](https://cloud.githubusercontent.com/assets/1694965/23700279/3d0a3cf0-03ea-11e7-85d4-0173680de050.png)

**Comment by scttnlsn** [comment]
Does it disconnect at the same point every time?  There's nothing about Dandelion that would depend on the PHP version on the remote server so I doubt that is the problem.  Did your hosting provider upgrade anything else about the server?  Perhaps the SFTP software they're running?

**Comment by kevwaddell** [comment]
It seems to have fixed it self and is now working fine. Very strange.
