### ISSUE TITLE
undefined symbol: rb_intern2

### ISSUE THREAD

**Issue by didierjulien** [scttnlsn/dandelion#162]
Hi, I've been running dandelion 0.5.0 for over a year now without any issues in my CI server. But for no apparent reason, I am getting a ruby error:
**/usr/local/rvm/gems/ruby-2.1.8/bin/dandelion: symbol lookup error: /usr/local/rvm/gems/ruby-2.1.8/gems/rugged-0.23.3/lib/rugged/rugged.so: undefined symbol: rb_intern2**
I tried to uninstall and reinstall the gem but no luck. 
I'm running ruby 2.1.8. Is this a version compatibility issue? if so, why would this only be happening now and affecting only dandelion?

**Comment by scttnlsn** [comment]
Looks like it might be an issue with Rugged (one of Dandelion's dependencies).  Not sure what the issue is specifically though- looks like something related to the native extensions that Rugged uses.  Could you try re-installing Rugged and see if that fixes the issue?  Or even the whole Ruby version and Gems?  If it's still an issue after that I'll look into it further.

**Comment by didierjulien** [comment]
Well i uninstalled the rugged gem, updated to ruby 2.3.0 and installed rugged 0.25.1.
This looked to have fixed the issue but broken my PATH.

**Comment by didierjulien** [comment]
I tried again in a new session and it's the same failure but now I can't reinstall rugged.
[root@xxxxxxx]# gem uninstall rugged

You have requested to uninstall the gem:
	rugged-0.23.3

dandelion-0.5.0 depends on rugged (= 0.23.3)
If you remove this gem, these dependencies will not be met.
Continue with Uninstall? [yN]  y
Successfully uninstalled rugged-0.23.3

[root@xxxxxxx]# gem install rugged
Fetching: rugged-0.25.1.1.gem (100%)
ERROR:  Error installing rugged:
	rugged requires Ruby version >= 1.9.3.

**Comment by didierjulien** [comment]
Alright, so I resolved the issue by uninstalling all gems and removing all versions of ruby. 
I then reinstalled RVM and installed only dandelion gem and net-sftp. 
After resetting the GEMPATH it seems everything is back on track. 
Thanks for the response! hope this helps anyone else with this issue.

**Comment by scttnlsn** [comment]
OK great.  Glad you figured it out.
