### ISSUE TITLE
Error trying to install dandelion

### ISSUE THREAD

**Issue by Ackman303** [scttnlsn/dandelion#167]
Hi,

I'm using linx mint OS.

I installed pkg-config and cmake, and when I try to intall dandelion I get this error:

Building native extensions.  This could take a while...
ERROR:  Error installing dandelion:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/rugged-0.26.0/ext/rugged
/usr/bin/ruby2.3 -r ./siteconf20180227-19395-14khg1o.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/rugged-0.26.0 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/rugged-0.26.0/gem_make.out

**Comment by scttnlsn** [comment]
Could you paste the contents of `/var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/rugged-0.26.0/gem_make.out`?

**Comment by Ackman303** [comment]
Hi,

thanks for your quick response!

yes, the content looks the same I posted in my message:

current directory: /var/lib/gems/2.3.0/gems/rugged-0.26.0/ext/rugged
/usr/bin/ruby2.3 -r ./siteconf20180227-19395-14khg1o.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

**Comment by scttnlsn** [comment]
Hmm, OK.  That's not really enough information for me to understand what is going on- I would have expected more output.  Could you try running `gem install rugged` (a dependency of Dandelion) and paste the entire output?

**Comment by Ackman303** [comment]
No worries.

I found the solution, I didn't have the ruby headers installed.
I'm pasting here just in case someone need it too:

For Debian, and other distributions using Debian style packaging the ruby development headers are installed by:
sudo apt-get install ruby-dev

For Ubuntu the ruby development headers are installed by:
sudo apt-get install ruby-all-dev

If you are using a earlier version of ruby (such as 2.2), then you will need to run:
sudo apt-get install ruby2.2-dev

(where 2.2 is your desired Ruby version)

Thanks Scott.

**Comment by scttnlsn** [comment]
Oh, great.  Glad you figured it out.  I typicall use `rbenv` to manage Ruby versions and I guess the headers come along with each Ruby install automatically.  I'll update the README in case others run into this as well.  Thanks a lot!
