### ISSUE TITLE
Updating to 0.5.4

### ISSUE THREAD

**Issue by tyssen** [scttnlsn/dandelion#171]
On OSX 10.13.6 I have 0.4.6 installed and I'm trying to update to 0.5.4 to be able to use the FTPS adapter and it seems to go through fine…

    gem install dandelion
    Building native extensions. This could take a while...
    Successfully installed rugged-0.27.7
    Fetching: dandelion-0.5.4.gem (100%)
    !   The 'dandelion' gem is installed but you may need to install additional
    !   gems depending on the adapters you intend to use.
    !
    !   Running 'dandelion status' in your project directory will indicate which
    !   additional gems need to be installed.
    Successfully installed dandelion-0.5.4
    Parsing documentation for rugged-0.27.7
    Installing ri documentation for rugged-0.27.7
    Parsing documentation for dandelion-0.5.4
    Installing ri documentation for dandelion-0.5.4
    Done installing documentation for rugged, dandelion after 1 seconds
    2 gems installed

but `dandelion -v` still says 0.4.6 and if I try to run dandelion on my repo I get

> Unsupported adapter: ftps

If I try to run `dandelion status` I get

> Sorry, cleartext sessions and weak ciphers are not accepted on this server.

if I use FTP and a timeout if I use SFTP.

**Comment by scttnlsn** [comment]
Are you using any sort of Ruby environment manager like Rbenv or RVM?  What Dandelion version is listed in the output of `gem list`?

**Comment by tyssen** [comment]
Sorry, should've come back to update this. I tried again a couple of days later and it was reporting the correct version and the new adapter was working OK. Not sure why as there were no restarts involved in between. :?
