### ISSUE TITLE
FTPS deploy issue

### ISSUE THREAD

**Issue by mediaformat** [scttnlsn/dandelion#174]
We're using the latest version [v0.5.4](https://github.com/scttnlsn/dandelion/releases/tag/v0.5.4),
but running into an issue with ftps
```
The ftps adapter requires additional gems:    double-bag-ftps
Please install the gems first: gem install double-bag-ftps
```
Despite `double-bag-ftps` being in installed

Could this be related to https://github.com/scttnlsn/dandelion/pull/166

**Comment by scttnlsn** [comment]
@mediaformat Have you tested #166?  I don't have a good way to test FTPS transfers.  If you're making FTPS transfers and #166 is working as expected then I can get that merged and deployed in a new version.

**Comment by mediaformat** [comment]
After testing and reviewing #166 we decided to implement the changes ourselves via #175.

> I don't have a good way to test FTPS transfers

We haven't tested dandelion with [this site](https://dlptest.com/ftp-test/), but have confirmed FTPS connections work via Filezilla.

**Comment by scttnlsn** [comment]
Fixed via https://github.com/scttnlsn/dandelion/pull/175
