### ISSUE TITLE
provide params on command line

### ISSUE THREAD

**Issue by yegor256** [scttnlsn/dandelion#80]
I'm trying to use dandelion together with Travis-CI, in order to deploy my public (!) repository through FTP to my private server. I can't do it at the moment, because I have to hard-code FTP password inside `dandelion.yml` file. That means that my FTP credentials will be publicly available in Github.

Instead, would be great to have an ability to run:

```
dandelion deploy -Dpassword=secret123
```

Then, in `dandelion.yml` I will use:

``` yaml
password: ${password}
```

**Comment by Polymetric** [comment]
Can this be added to the readme? It's pretty useful info.

**Comment by scttnlsn** [comment]
@Polymetric Good call.  Added this to the README (https://github.com/scttnlsn/dandelion/commit/58b4c21e91456d0e0f96affe3205a3054195f232)
