### ISSUE TITLE
Worked great for 3 deploys and then stopped working

### ISSUE THREAD

**Issue by ghost** [scttnlsn/dandelion#81]
I'm not sure what happened here. After I amended a commit Dandelion stopped deploying. Any suggestions? 

Writing file:  plancorp2014/functions.php
/Users/812studio/.rvm/gems/ruby-2.1.1/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:846:in `wait_for': Net::SFTP::StatusException (3, "permission denied") (Net::SFTP::StatusException)
    from /Users/812studio/.rvm/gems/ruby-2.1.1/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:371:in`setstat!'
    from /Users/812studio/.rvm/gems/ruby-2.1.1/gems/dandelion-0.4.4/lib/dandelion/adapter/sftp.rb:45:in `write'
    from /Users/812studio/.rvm/gems/ruby-2.1.1/gems/dandelion-0.4.4/lib/dandelion/deployer.rb:49:in`deploy_change!'
    from /Users/812studio/.rvm/gems/ruby-2.1.1/gems/dandelion-0.4.4/lib/dandelion/deployer.rb:13:in `block in deploy_changeset!'
    from /Users/812studio/.rvm/gems/ruby-2.1.1/gems/dandelion-0.4.4/lib/dandelion/changeset.rb:28:in`block in each'
    from /Users/812studio/.rvm/gems/ruby-2.1.1/gems/dandelion-0.4.4/lib/dandelion/diff.rb:41:in `block in each'
    from /Users/812studio/.rvm/gems/ruby-2.1.1/gems/dandelion-0.4.4/lib/dandelion/diff.rb:37:in`each'
    from /Users/812studio/.rvm/gems/ruby-2.1.1/gems/dandelion-0.4.4/lib/dandelion/diff.rb:37:in `each'
    from /Users/812studio/.rvm/gems/ruby-2.1.1/gems/dandelion-0.4.4/lib/dandelion/changeset.rb:20:in`each'
    from /Users/812studio/.rvm/gems/ruby-2.1.1/gems/dandelion-0.4.4/lib/dandelion/deployer.rb:9:in `deploy_changeset!'
    from /Users/812studio/.rvm/gems/ruby-2.1.1/gems/dandelion-0.4.4/lib/dandelion/command/deploy.rb:55:in`deploy_changeset!'
    from /Users/812studio/.rvm/gems/ruby-2.1.1/gems/dandelion-0.4.4/lib/dandelion/command/deploy.rb:30:in `execute!'
    from /Users/812studio/.rvm/gems/ruby-2.1.1/gems/dandelion-0.4.4/lib/dandelion/cli.rb:66:in`execute!'
    from /Users/812studio/.rvm/gems/ruby-2.1.1/gems/dandelion-0.4.4/bin/dandelion:8:in `<top (required)>'
    from /Users/812studio/.rvm/gems/ruby-2.1.1/bin/dandelion:23:in`load'
    from /Users/812studio/.rvm/gems/ruby-2.1.1/bin/dandelion:23:in `<main>'
    from /Users/812studio/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in`eval'
    from /Users/812studio/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by aritradatta** [comment]
I am having a similar issue - i can write the files just fine using an SFTP client like FileZilla using the same login credentials, but when I try to do it through Dandelion for a certain folder it errors out.

Remote revision:    40892ac41630f88a247bf111e8ee73c931fc03e6
Deploying revision: 5f06b1aac5fb073f633a7348724cdc77ccb3d46f
Deploying changes...
Writing file:  application/controllers/Gettingstarted.php
/var/lib/gems/2.3.0/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:846:in `wait_for': Net::SFTP::StatusException (3, "permission denied") (Net::SFTP::StatusException)
	from /var/lib/gems/2.3.0/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:371:in `setstat!'
	from /var/lib/gems/2.3.0/gems/dandelion-0.5.0/lib/dandelion/adapter/sftp.rb:45:in `write'
	from /var/lib/gems/2.3.0/gems/dandelion-0.5.0/lib/dandelion/deployer.rb:49:in `deploy_change!'
	from /var/lib/gems/2.3.0/gems/dandelion-0.5.0/lib/dandelion/deployer.rb:13:in `block in deploy_changeset!'
	from /var/lib/gems/2.3.0/gems/dandelion-0.5.0/lib/dandelion/changeset.rb:32:in `block in each'
	from /var/lib/gems/2.3.0/gems/dandelion-0.5.0/lib/dandelion/diff.rb:39:in `block in each'
	from /var/lib/gems/2.3.0/gems/dandelion-0.5.0/lib/dandelion/diff.rb:39:in `each'
	from /var/lib/gems/2.3.0/gems/dandelion-0.5.0/lib/dandelion/diff.rb:39:in `each'
	from /var/lib/gems/2.3.0/gems/dandelion-0.5.0/lib/dandelion/changeset.rb:20:in `each'
	from /var/lib/gems/2.3.0/gems/dandelion-0.5.0/lib/dandelion/deployer.rb:9:in `deploy_changeset!'
	from /var/lib/gems/2.3.0/gems/dandelion-0.5.0/lib/dandelion/command/deploy.rb:55:in `deploy_changeset!'
	from /var/lib/gems/2.3.0/gems/dandelion-0.5.0/lib/dandelion/command/deploy.rb:30:in `execute!'
	from /var/lib/gems/2.3.0/gems/dandelion-0.5.0/lib/dandelion/cli.rb:73:in `execute!'
	from /var/lib/gems/2.3.0/gems/dandelion-0.5.0/bin/dandelion:8:in `<top (required)>'
	from /usr/local/bin/dandelion:23:in `load'
	from /usr/local/bin/dandelion:23:in `<main>'
